spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/passionatetour?characterEncoding=UTF-8&serverTimezone=UTC
    username: 'user_Id'
    password: 'user_Password'

  jpa:
    hibernate:
      #naming:
      #  physical-stragtegy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      #  ddl-auto: create
    properties:
      hibernate:

        # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace

temp.path: D:\upload